name: rdkitconverter
channels:
  - uclcheminformatics 
  - conda-forge
  - defaults
dependencies:
  - bokeh=3.2.0
  - mols2grid=1.1.1
  - networkx=3.1
  - pandas=2.0.2
  - python=3.10.11
  - rdkit=2022.09.1
  - scaffoldgraph=1.1.2
  - tqdm=4.65.0
  - numpy=1.25.0
  - pydot=1.4.2
  - pygraphviz=1.11
  - scipy=1.9.3
